<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:ns="http://injenity.net" 
xmlns:ns1="http://org.apache.axis2/xsd" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://injenity.net">
    <wsdl:documentation>
		Please Type your service description here
	</wsdl:documentation>
    <wsdl:types>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://injenity.net">
            <xs:element name="getDate">
                <xs:complexType>
                    <xs:sequence/>
                </xs:complexType>
            </xs:element>
            <xs:element name="getDateResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="return" nillable="true" type="xs:date"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="getDateRequest">
        <wsdl:part element="ns:getDate" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="getDateResponse">
        <wsdl:part element="ns:getDateResponse" name="parameters"/>
    </wsdl:message>
    <wsdl:portType name="TimeProviderPortType">
        <wsdl:operation name="getDate">
            <wsdl:input message="ns:getDateRequest" wsaw:Action="urn:getDate"/>
            <wsdl:output message="ns:getDateResponse" wsaw:Action="urn:getDateResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="TimeProviderSoap11Binding" type="ns:TimeProviderPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getDate">
            <soap:operation soapAction="urn:getDate" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="TimeProviderSoap12Binding" type="ns:TimeProviderPortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getDate">
            <soap12:operation soapAction="urn:getDate" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="TimeProviderHttpBinding" type="ns:TimeProviderPortType">
        <http:binding verb="POST"/>
        <wsdl:operation name="getDate">
            <http:operation location="getDate"/>
            <wsdl:input>
                <mime:content part="parameters" type="application/xml"/>
            </wsdl:input>
            <wsdl:output>
                <mime:content part="parameters" type="application/xml"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="TimeProvider">
        <wsdl:port binding="ns:TimeProviderSoap11Binding" name="TimeProviderHttpSoap11Endpoint">
            <soap:address location="http://localhost:9090/DateTimeServiceADB/services/TimeProviderHttpSoap11Endpoint"/>
        </wsdl:port>
        <wsdl:port binding="ns:TimeProviderSoap12Binding" name="TimeProviderHttpSoap12Endpoint">
            <soap12:address location="http://localhost:9090/DateTimeService/services/TimeProvider.TimeProviderHttpSoap12Endpoint/"/>
        </wsdl:port>
        <wsdl:port binding="ns:TimeProviderHttpBinding" name="TimeProviderHttpEndpoint">
            <http:address location="http://localhost:9090/DateTimeService/services/TimeProvider.TimeProviderHttpEndpoint/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
